### ISSUE TITLE
Add general `proc`-like function

### ISSUE THREAD

**Issue by vil02** [vil02/string_to_code_proj#163]
1. [x] Add general `proc`-like function, where the _target language_ is specified as one of the arguments (done in #165).
2. [x] Add functionality allowing to query available target languages (done in #164).
3. [x] Add examples illustrating usage of these features (done in #166).
